#!/usr/bin/env python3
"""
==============================================================================
物体 Retention 题库生成脚本
==============================================================================

功能：
  生成物体 retention 池，用于训练时防止灾难性遗忘。
  - 8 GPU 并行生成物体图片（SDXL-Turbo）
  - 自动生成 CW / MCQ I2D / MCQ D2I 题目
  - 包含约 2000+ 种常见物体（颜色、大小、材质变体）

==============================================================================
使用方法
==============================================================================

# 生成物体 retention 池
python scripts/generate_object_retention_pool.py \
    --num_objects 200 \
    --output_dir data/object_retention_pool \
    --num_gpus 8

# 指定随机种子
python scripts/generate_object_retention_pool.py \
    --num_objects 100 \
    --output_dir data/object_retention_pool \
    --seed 123

==============================================================================
参数说明
==============================================================================

  --num_objects     要生成的物体数量 (默认: 200)
  --output_dir      输出目录 (默认: data/object_retention_pool)
  --num_gpus        使用的 GPU 数量 (默认: 8)
  --seed            随机种子 (默认: 42)

==============================================================================
输出结构
==============================================================================

data/object_retention_pool/
├── objects.json         # 物体描述元信息
├── pool_meta.json       # 生成参数记录
├── images/              # 物体图片 (object_0000.png, ...)
├── cw_train.jsonl       # Correct/Wrong 训练数据
├── cw_val.jsonl         # Correct/Wrong 验证数据
├── mcq_i2d_train.jsonl  # MCQ Image→Description 训练数据
├── mcq_i2d_val.jsonl    # MCQ Image→Description 验证数据
├── mcq_d2i_train.jsonl  # MCQ Description→Image 训练数据
└── mcq_d2i_val.jsonl    # MCQ Description→Image 验证数据

==============================================================================
注意事项
==============================================================================

  - 物体池与人脸池是独立的，可以同时使用也可以只用其中一个
  - 训练时通过 --retention_pool 参数指定物体池路径
  - 默认只使用人脸池（--face_retention_ratio=1.0）
  - 物体池包含约 2000+ 种常见物体（颜色、大小、材质变体）

==============================================================================
"""

import argparse
import json
import os
import random
import math
import subprocess
import tempfile
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor

import yaml

# SDXL 模型路径
SDXL_MODEL_PATH = "/work/models/AI-ModelScope/sdxl-turbo"

# 常见物体列表（用于生成 retention 图片）
COMMON_OBJECTS = [
    "accordion",
    "action figure",
    "air fryer",
    "airplane",
    "aluminum bowl",
    "aluminum box",
    "aluminum cabinet",
    "aluminum chair",
    "aluminum cup",
    "aluminum door",
    "aluminum fork",
    "aluminum frame",
    "aluminum plate",
    "aluminum sculpture",
    "aluminum spoon",
    "aluminum statue",
    "aluminum table",
    "aluminum vase",
    "ambulance",
    "amethyst",
    "amplifier",
    "apple",
    "apricot",
    "armchair",
    "artichoke",
    "asparagus",
    "baby bottle",
    "baby monitor",
    "baby stroller",
    "backpack",
    "bacon",
    "bagel",
    "balloon",
    "bamboo bowl",
    "bamboo box",
    "bamboo cabinet",
    "bamboo chair",
    "bamboo cup",
    "bamboo door",
    "bamboo fork",
    "bamboo frame",
    "bamboo plate",
    "bamboo sculpture",
    "bamboo shoot",
    "bamboo spoon",
    "bamboo statue",
    "bamboo table",
    "bamboo vase",
    "banana",
    "bandage",
    "banjo",
    "baobab tree",
    "barn",
    "baseball bat",
    "basketball",
    "beach",
    "bear",
    "bed",
    "bee",
    "beet",
    "beige apple",
    "beige apricot",
    "beige artichoke",
    "beige asparagus",
    "beige banana",
    "beige bear",
    "beige beet",
    "beige bell pepper",
    "beige bird",
    "beige blackberry",
    "beige blueberry",
    "beige broccoli",
    "beige brussels sprout",
    "beige cabbage",
    "beige cantaloupe",
    "beige carrot",
    "beige cat",
    "beige cauliflower",
    "beige celery",
    "beige cheetah",
    "beige cherry",
    "beige chimp",
    "beige coconut",
    "beige corn",
    "beige cow",
    "beige cranberry",
    "beige cucumber",
    "beige date",
    "beige deer",
    "beige dog",
    "beige dolphin",
    "beige dragon fruit",
    "beige duck",
    "beige eagle",
    "beige eggplant",
    "beige elephant",
    "beige fig",
    "beige flamingo",
    "beige fox",
    "beige frog",
    "beige garlic",
    "beige ginger",
    "beige giraffe",
    "beige gorilla",
    "beige grapefruit",
    "beige grapes",
    "beige green bean",
    "beige guava",
    "beige hippo",
    "beige honeydew",
    "beige horse",
    "beige hummingbird",
    "beige kangaroo",
    "beige kiwi",
    "beige koala",
    "beige leek",
    "beige lemon",
    "beige lettuce",
    "beige lion",
    "beige mango",
    "beige mushroom",
    "beige onion",
    "beige orange",
    "beige orangutan",
    "beige owl",
    "beige panda",
    "beige papaya",
    "beige parrot",
    "beige passion fruit",
    "beige pea",
    "beige peach",
    "beige peacock",
    "beige pelican",
    "beige penguin",
    "beige persimmon",
    "beige pig",
    "beige pineapple",
    "beige plum",
    "beige polar bear",
    "beige pomegranate",
    "beige potato",
    "beige pumpkin",
    "beige rabbit",
    "beige radish",
    "beige raspberry",
    "beige rhino",
    "beige rooster",
    "beige sheep",
    "beige spinach",
    "beige squash",
    "beige strawberry",
    "beige swan",
    "beige sweet potato",
    "beige tiger",
    "beige tomato",
    "beige turnip",
    "beige watermelon",
    "beige wolf",
    "beige zebra",
    "beige zucchini",
    "bell pepper",
    "bicycle",
    "billiard ball",
    "binder",
    "binoculars",
    "bird",
    "birthday cake",
    "black apple",
    "black apricot",
    "black artichoke",
    "black asparagus",
    "black banana",
    "black bear",
    "black beet",
    "black bell pepper",
    "black bird",
    "black blackberry",
    "black blueberry",
    "black broccoli",
    "black brussels sprout",
    "black cabbage",
    "black cantaloupe",
    "black carrot",
    "black cat",
    "black cauliflower",
    "black celery",
    "black cheetah",
    "black cherry",
    "black chimp",
    "black coconut",
    "black corn",
    "black cow",
    "black cranberry",
    "black cucumber",
    "black date",
    "black deer",
    "black dog",
    "black dolphin",
    "black dragon fruit",
    "black duck",
    "black eagle",
    "black eggplant",
    "black elephant",
    "black fig",
    "black flamingo",
    "black fox",
    "black frog",
    "black garlic",
    "black ginger",
    "black giraffe",
    "black gorilla",
    "black grapefruit",
    "black grapes",
    "black green bean",
    "black guava",
    "black hippo",
    "black honeydew",
    "black horse",
    "black hummingbird",
    "black kangaroo",
    "black kiwi",
    "black koala",
    "black leek",
    "black lemon",
    "black lettuce",
    "black lion",
    "black mango",
    "black mushroom",
    "black onion",
    "black orange",
    "black orangutan",
    "black owl",
    "black panda",
    "black papaya",
    "black parrot",
    "black passion fruit",
    "black pea",
    "black peach",
    "black peacock",
    "black pelican",
    "black penguin",
    "black persimmon",
    "black pig",
    "black pineapple",
    "black plum",
    "black polar bear",
    "black pomegranate",
    "black potato",
    "black pumpkin",
    "black rabbit",
    "black radish",
    "black raspberry",
    "black rhino",
    "black rooster",
    "black sheep",
    "black spinach",
    "black squash",
    "black strawberry",
    "black swan",
    "black sweet potato",
    "black tiger",
    "black tomato",
    "black turnip",
    "black watermelon",
    "black wolf",
    "black zebra",
    "black zucchini",
    "blackberry",
    "blanket",
    "blender",
    "blue apple",
    "blue apricot",
    "blue artichoke",
    "blue asparagus",
    "blue banana",
    "blue bear",
    "blue beet",
    "blue bell pepper",
    "blue bird",
    "blue blackberry",
    "blue blueberry",
    "blue broccoli",
    "blue brussels sprout",
    "blue cabbage",
    "blue cantaloupe",
    "blue carrot",
    "blue cat",
    "blue cauliflower",
    "blue celery",
    "blue cheetah",
    "blue cherry",
    "blue chimp",
    "blue coconut",
    "blue corn",
    "blue cow",
    "blue cranberry",
    "blue cucumber",
    "blue date",
    "blue deer",
    "blue dog",
    "blue dolphin",
    "blue dragon fruit",
    "blue duck",
    "blue eagle",
    "blue eggplant",
    "blue elephant",
    "blue fig",
    "blue flamingo",
    "blue fox",
    "blue frog",
    "blue garlic",
    "blue ginger",
    "blue giraffe",
    "blue gorilla",
    "blue grapefruit",
    "blue grapes",
    "blue green bean",
    "blue guava",
    "blue hippo",
    "blue honeydew",
    "blue horse",
    "blue hummingbird",
    "blue kangaroo",
    "blue kiwi",
    "blue koala",
    "blue leek",
    "blue lemon",
    "blue lettuce",
    "blue lion",
    "blue mango",
    "blue mushroom",
    "blue onion",
    "blue orange",
    "blue orangutan",
    "blue owl",
    "blue panda",
    "blue papaya",
    "blue parrot",
    "blue passion fruit",
    "blue pea",
    "blue peach",
    "blue peacock",
    "blue pelican",
    "blue penguin",
    "blue persimmon",
    "blue pig",
    "blue pineapple",
    "blue plum",
    "blue polar bear",
    "blue pomegranate",
    "blue potato",
    "blue pumpkin",
    "blue rabbit",
    "blue radish",
    "blue raspberry",
    "blue rhino",
    "blue rooster",
    "blue sheep",
    "blue spinach",
    "blue squash",
    "blue strawberry",
    "blue swan",
    "blue sweet potato",
    "blue tiger",
    "blue tomato",
    "blue turnip",
    "blue watermelon",
    "blue wolf",
    "blue zebra",
    "blue zucchini",
    "blueberry",
    "board game",
    "boat",
    "bonsai tree",
    "book",
    "bookshelf",
    "boots",
    "boulder",
    "bowl",
    "bowling ball",
    "boxing glove",
    "bracelet",
    "bridge",
    "broccoli",
    "bronze bowl",
    "bronze box",
    "bronze cabinet",
    "bronze chair",
    "bronze cup",
    "bronze door",
    "bronze fork",
    "bronze frame",
    "bronze plate",
    "bronze sculpture",
    "bronze spoon",
    "bronze statue",
    "bronze table",
    "bronze vase",
    "broom",
    "brown apple",
    "brown apricot",
    "brown artichoke",
    "brown asparagus",
    "brown banana",
    "brown bear",
    "brown beet",
    "brown bell pepper",
    "brown bird",
    "brown blackberry",
    "brown blueberry",
    "brown broccoli",
    "brown brussels sprout",
    "brown cabbage",
    "brown cantaloupe",
    "brown carrot",
    "brown cat",
    "brown cauliflower",
    "brown celery",
    "brown cheetah",
    "brown cherry",
    "brown chimp",
    "brown coconut",
    "brown corn",
    "brown cow",
    "brown cranberry",
    "brown cucumber",
    "brown date",
    "brown deer",
    "brown dog",
    "brown dolphin",
    "brown dragon fruit",
    "brown duck",
    "brown eagle",
    "brown eggplant",
    "brown elephant",
    "brown fig",
    "brown flamingo",
    "brown fox",
    "brown frog",
    "brown garlic",
    "brown ginger",
    "brown giraffe",
    "brown gorilla",
    "brown grapefruit",
    "brown grapes",
    "brown green bean",
    "brown guava",
    "brown hippo",
    "brown honeydew",
    "brown horse",
    "brown hummingbird",
    "brown kangaroo",
    "brown kiwi",
    "brown koala",
    "brown leek",
    "brown lemon",
    "brown lettuce",
    "brown lion",
    "brown mango",
    "brown mushroom",
    "brown onion",
    "brown orange",
    "brown orangutan",
    "brown owl",
    "brown panda",
    "brown papaya",
    "brown parrot",
    "brown passion fruit",
    "brown pea",
    "brown peach",
    "brown peacock",
    "brown pelican",
    "brown penguin",
    "brown persimmon",
    "brown pig",
    "brown pineapple",
    "brown plum",
    "brown polar bear",
    "brown pomegranate",
    "brown potato",
    "brown pumpkin",
    "brown rabbit",
    "brown radish",
    "brown raspberry",
    "brown rhino",
    "brown rooster",
    "brown sheep",
    "brown spinach",
    "brown squash",
    "brown strawberry",
    "brown swan",
    "brown sweet potato",
    "brown tiger",
    "brown tomato",
    "brown turnip",
    "brown watermelon",
    "brown wolf",
    "brown zebra",
    "brown zucchini",
    "brownie",
    "brush",
    "brussels sprout",
    "bucket",
    "bulletin board",
    "burrito",
    "bus",
    "bust",
    "butterfly",
    "cabbage",
    "cabin",
    "cabinet",
    "cactus",
    "cake",
    "calculator",
    "calendar",
    "camera",
    "campfire",
    "candle",
    "candy cane",
    "cantaloupe",
    "canvas",
    "canyon",
    "car",
    "car seat",
    "carrot",
    "cassette tape",
    "castle",
    "cat",
    "cauliflower",
    "cd",
    "celery",
    "cello",
    "ceramic bowl",
    "ceramic box",
    "ceramic cabinet",
    "ceramic chair",
    "ceramic cup",
    "ceramic door",
    "ceramic fork",
    "ceramic frame",
    "ceramic plate",
    "ceramic sculpture",
    "ceramic spoon",
    "ceramic statue",
    "ceramic table",
    "ceramic vase",
    "chair",
    "chandelier",
    "cheesecake",
    "cheetah",
    "cherry",
    "cherry blossom",
    "chess piece",
    "chess set",
    "chimp",
    "christmas tree",
    "church",
    "clarinet",
    "clock",
    "cloud",
    "coat",
    "coconut",
    "coffee machine",
    "compass",
    "concrete bowl",
    "concrete box",
    "concrete cabinet",
    "concrete chair",
    "concrete cup",
    "concrete door",
    "concrete fork",
    "concrete frame",
    "concrete plate",
    "concrete sculpture",
    "concrete spoon",
    "concrete statue",
    "concrete table",
    "concrete vase",
    "cookie",
    "cooler",
    "copper bowl",
    "copper box",
    "copper cabinet",
    "copper chair",
    "copper cup",
    "copper door",
    "copper fork",
    "copper frame",
    "copper plate",
    "copper sculpture",
    "copper spoon",
    "copper statue",
    "copper table",
    "copper vase",
    "coral apple",
    "coral apricot",
    "coral artichoke",
    "coral asparagus",
    "coral banana",
    "coral bear",
    "coral beet",
    "coral bell pepper",
    "coral bird",
    "coral blackberry",
    "coral blueberry",
    "coral broccoli",
    "coral brussels sprout",
    "coral cabbage",
    "coral cantaloupe",
    "coral carrot",
    "coral cat",
    "coral cauliflower",
    "coral celery",
    "coral cheetah",
    "coral cherry",
    "coral chimp",
    "coral coconut",
    "coral corn",
    "coral cow",
    "coral cranberry",
    "coral cucumber",
    "coral date",
    "coral deer",
    "coral dog",
    "coral dolphin",
    "coral dragon fruit",
    "coral duck",
    "coral eagle",
    "coral eggplant",
    "coral elephant",
    "coral fig",
    "coral flamingo",
    "coral fox",
    "coral frog",
    "coral garlic",
    "coral ginger",
    "coral giraffe",
    "coral gorilla",
    "coral grapefruit",
    "coral grapes",
    "coral green bean",
    "coral guava",
    "coral hippo",
    "coral honeydew",
    "coral horse",
    "coral hummingbird",
    "coral kangaroo",
    "coral kiwi",
    "coral koala",
    "coral leek",
    "coral lemon",
    "coral lettuce",
    "coral lion",
    "coral mango",
    "coral mushroom",
    "coral onion",
    "coral orange",
    "coral orangutan",
    "coral owl",
    "coral panda",
    "coral papaya",
    "coral parrot",
    "coral passion fruit",
    "coral pea",
    "coral peach",
    "coral peacock",
    "coral pelican",
    "coral penguin",
    "coral persimmon",
    "coral pig",
    "coral pineapple",
    "coral plum",
    "coral polar bear",
    "coral pomegranate",
    "coral potato",
    "coral pumpkin",
    "coral rabbit",
    "coral radish",
    "coral raspberry",
    "coral rhino",
    "coral rooster",
    "coral sheep",
    "coral spinach",
    "coral squash",
    "coral strawberry",
    "coral swan",
    "coral sweet potato",
    "coral tiger",
    "coral tomato",
    "coral turnip",
    "coral watermelon",
    "coral wolf",
    "coral zebra",
    "coral zucchini",
    "corn",
    "cottage",
    "cotton bowl",
    "cotton box",
    "cotton cabinet",
    "cotton chair",
    "cotton cup",
    "cotton door",
    "cotton fork",
    "cotton frame",
    "cotton plate",
    "cotton sculpture",
    "cotton spoon",
    "cotton statue",
    "cotton table",
    "cotton vase",
    "cow",
    "cranberry",
    "crib",
    "crimson apple",
    "crimson apricot",
    "crimson artichoke",
    "crimson asparagus",
    "crimson banana",
    "crimson bear",
    "crimson beet",
    "crimson bell pepper",
    "crimson bird",
    "crimson blackberry",
    "crimson blueberry",
    "crimson broccoli",
    "crimson brussels sprout",
    "crimson cabbage",
    "crimson cantaloupe",
    "crimson carrot",
    "crimson cat",
    "crimson cauliflower",
    "crimson celery",
    "crimson cheetah",
    "crimson cherry",
    "crimson chimp",
    "crimson coconut",
    "crimson corn",
    "crimson cow",
    "crimson cranberry",
    "crimson cucumber",
    "crimson date",
    "crimson deer",
    "crimson dog",
    "crimson dolphin",
    "crimson dragon fruit",
    "crimson duck",
    "crimson eagle",
    "crimson eggplant",
    "crimson elephant",
    "crimson fig",
    "crimson flamingo",
    "crimson fox",
    "crimson frog",
    "crimson garlic",
    "crimson ginger",
    "crimson giraffe",
    "crimson gorilla",
    "crimson grapefruit",
    "crimson grapes",
    "crimson green bean",
    "crimson guava",
    "crimson hippo",
    "crimson honeydew",
    "crimson horse",
    "crimson hummingbird",
    "crimson kangaroo",
    "crimson kiwi",
    "crimson koala",
    "crimson leek",
    "crimson lemon",
    "crimson lettuce",
    "crimson lion",
    "crimson mango",
    "crimson mushroom",
    "crimson onion",
    "crimson orange",
    "crimson orangutan",
    "crimson owl",
    "crimson panda",
    "crimson papaya",
    "crimson parrot",
    "crimson passion fruit",
    "crimson pea",
    "crimson peach",
    "crimson peacock",
    "crimson pelican",
    "crimson penguin",
    "crimson persimmon",
    "crimson pig",
    "crimson pineapple",
    "crimson plum",
    "crimson polar bear",
    "crimson pomegranate",
    "crimson potato",
    "crimson pumpkin",
    "crimson rabbit",
    "crimson radish",
    "crimson raspberry",
    "crimson rhino",
    "crimson rooster",
    "crimson sheep",
    "crimson spinach",
    "crimson squash",
    "crimson strawberry",
    "crimson swan",
    "crimson sweet potato",
    "crimson tiger",
    "crimson tomato",
    "crimson turnip",
    "crimson watermelon",
    "crimson wolf",
    "crimson zebra",
    "crimson zucchini",
    "crocodile",
    "croissant",
    "crow",
    "crutch",
    "crystal bowl",
    "crystal box",
    "crystal cabinet",
    "crystal chair",
    "crystal cup",
    "crystal door",
    "crystal fork",
    "crystal frame",
    "crystal plate",
    "crystal sculpture",
    "crystal spoon",
    "crystal statue",
    "crystal table",
    "crystal vase",
    "cucumber",
    "cupcake",
    "curry",
    "curtain",
    "cutting board",
    "cyan apple",
    "cyan apricot",
    "cyan artichoke",
    "cyan asparagus",
    "cyan banana",
    "cyan bear",
    "cyan beet",
    "cyan bell pepper",
    "cyan bird",
    "cyan blackberry",
    "cyan blueberry",
    "cyan broccoli",
    "cyan brussels sprout",
    "cyan cabbage",
    "cyan cantaloupe",
    "cyan carrot",
    "cyan cat",
    "cyan cauliflower",
    "cyan celery",
    "cyan cheetah",
    "cyan cherry",
    "cyan chimp",
    "cyan coconut",
    "cyan corn",
    "cyan cow",
    "cyan cranberry",
    "cyan cucumber",
    "cyan date",
    "cyan deer",
    "cyan dog",
    "cyan dolphin",
    "cyan dragon fruit",
    "cyan duck",
    "cyan eagle",
    "cyan eggplant",
    "cyan elephant",
    "cyan fig",
    "cyan flamingo",
    "cyan fox",
    "cyan frog",
    "cyan garlic",
    "cyan ginger",
    "cyan giraffe",
    "cyan gorilla",
    "cyan grapefruit",
    "cyan grapes",
    "cyan green bean",
    "cyan guava",
    "cyan hippo",
    "cyan honeydew",
    "cyan horse",
    "cyan hummingbird",
    "cyan kangaroo",
    "cyan kiwi",
    "cyan koala",
    "cyan leek",
    "cyan lemon",
    "cyan lettuce",
    "cyan lion",
    "cyan mango",
    "cyan mushroom",
    "cyan onion",
    "cyan orange",
    "cyan orangutan",
    "cyan owl",
    "cyan panda",
    "cyan papaya",
    "cyan parrot",
    "cyan passion fruit",
    "cyan pea",
    "cyan peach",
    "cyan peacock",
    "cyan pelican",
    "cyan penguin",
    "cyan persimmon",
    "cyan pig",
    "cyan pineapple",
    "cyan plum",
    "cyan polar bear",
    "cyan pomegranate",
    "cyan potato",
    "cyan pumpkin",
    "cyan rabbit",
    "cyan radish",
    "cyan raspberry",
    "cyan rhino",
    "cyan rooster",
    "cyan sheep",
    "cyan spinach",
    "cyan squash",
    "cyan strawberry",
    "cyan swan",
    "cyan sweet potato",
    "cyan tiger",
    "cyan tomato",
    "cyan turnip",
    "cyan watermelon",
    "cyan wolf",
    "cyan zebra",
    "cyan zucchini",
    "daisy",
    "dart",
    "date",
    "deer",
    "desert",
    "desk",
    "desk organizer",
    "diamond",
    "diaper",
    "dice",
    "dishwasher",
    "dog",
    "doll",
    "dolphin",
    "domino",
    "donut",
    "dragon fruit",
    "dragonfly",
    "dress",
    "dresser",
    "drill",
    "drone",
    "drum",
    "duck",
    "dumbbell",
    "dustpan",
    "eagle",
    "easel",
    "easter egg",
    "eggplant",
    "elephant",
    "emerald",
    "envelope",
    "fabric bowl",
    "fabric box",
    "fabric cabinet",
    "fabric chair",
    "fabric cup",
    "fabric door",
    "fabric fork",
    "fabric frame",
    "fabric plate",
    "fabric sculpture",
    "fabric spoon",
    "fabric statue",
    "fabric table",
    "fabric vase",
    "fern",
    "fig",
    "fire truck",
    "firework",
    "first aid kit",
    "fishing rod",
    "flamingo",
    "flashlight",
    "flute",
    "folder",
    "food processor",
    "football",
    "forest",
    "fox",
    "french fries",
    "fried chicken",
    "frisbee",
    "frog",
    "game controller",
    "garlic",
    "giant apple",
    "giant apricot",
    "giant asparagus",
    "giant banana",
    "giant bell pepper",
    "giant blackberry",
    "giant blueberry",
    "giant broccoli",
    "giant cabbage",
    "giant cantaloupe",
    "giant carrot",
    "giant cauliflower",
    "giant celery",
    "giant cherry",
    "giant coconut",
    "giant corn",
    "giant cranberry",
    "giant cucumber",
    "giant date",
    "giant dragon fruit",
    "giant eggplant",
    "giant fig",
    "giant grapefruit",
    "giant grapes",
    "giant guava",
    "giant honeydew",
    "giant kiwi",
    "giant lemon",
    "giant lettuce",
    "giant mango",
    "giant mushroom",
    "giant onion",
    "giant orange",
    "giant papaya",
    "giant passion fruit",
    "giant peach",
    "giant persimmon",
    "giant pineapple",
    "giant plum",
    "giant pomegranate",
    "giant potato",
    "giant pumpkin",
    "giant radish",
    "giant raspberry",
    "giant spinach",
    "giant squash",
    "giant strawberry",
    "giant tomato",
    "giant watermelon",
    "giant zucchini",
    "gift box",
    "ginger",
    "giraffe",
    "glacier",
    "glass bowl",
    "glass box",
    "glass cabinet",
    "glass chair",
    "glass cup",
    "glass door",
    "glass fork",
    "glass frame",
    "glass plate",
    "glass sculpture",
    "glass spoon",
    "glass statue",
    "glass table",
    "glass vase",
    "globe",
    "gold apple",
    "gold apricot",
    "gold artichoke",
    "gold asparagus",
    "gold banana",
    "gold bear",
    "gold beet",
    "gold bell pepper",
    "gold bird",
    "gold blackberry",
    "gold blueberry",
    "gold broccoli",
    "gold brussels sprout",
    "gold cabbage",
    "gold cantaloupe",
    "gold carrot",
    "gold cat",
    "gold cauliflower",
    "gold celery",
    "gold cheetah",
    "gold cherry",
    "gold chimp",
    "gold coconut",
    "gold corn",
    "gold cow",
    "gold cranberry",
    "gold cucumber",
    "gold date",
    "gold deer",
    "gold dog",
    "gold dolphin",
    "gold dragon fruit",
    "gold duck",
    "gold eagle",
    "gold eggplant",
    "gold elephant",
    "gold fig",
    "gold flamingo",
    "gold fox",
    "gold frog",
    "gold garlic",
    "gold ginger",
    "gold giraffe",
    "gold gorilla",
    "gold grapefruit",
    "gold grapes",
    "gold green bean",
    "gold guava",
    "gold hippo",
    "gold honeydew",
    "gold horse",
    "gold hummingbird",
    "gold kangaroo",
    "gold kiwi",
    "gold koala",
    "gold leek",
    "gold lemon",
    "gold lettuce",
    "gold lion",
    "gold mango",
    "gold mushroom",
    "gold onion",
    "gold orange",
    "gold orangutan",
    "gold owl",
    "gold panda",
    "gold papaya",
    "gold parrot",
    "gold passion fruit",
    "gold pea",
    "gold peach",
    "gold peacock",
    "gold pelican",
    "gold penguin",
    "gold persimmon",
    "gold pig",
    "gold pineapple",
    "gold plum",
    "gold polar bear",
    "gold pomegranate",
    "gold potato",
    "gold pumpkin",
    "gold rabbit",
    "gold radish",
    "gold raspberry",
    "gold rhino",
    "gold rooster",
    "gold sheep",
    "gold spinach",
    "gold squash",
    "gold strawberry",
    "gold swan",
    "gold sweet potato",
    "gold tiger",
    "gold tomato",
    "gold turnip",
    "gold watermelon",
    "gold wolf",
    "gold zebra",
    "gold zucchini",
    "goldfish",
    "golf cart",
    "golf club",
    "gorilla",
    "granite bowl",
    "granite box",
    "granite cabinet",
    "granite chair",
    "granite cup",
    "granite door",
    "granite fork",
    "granite frame",
    "granite plate",
    "granite sculpture",
    "granite spoon",
    "granite statue",
    "granite table",
    "granite vase",
    "grapefruit",
    "grapes",
    "gray apple",
    "gray apricot",
    "gray artichoke",
    "gray asparagus",
    "gray banana",
    "gray bear",
    "gray beet",
    "gray bell pepper",
    "gray bird",
    "gray blackberry",
    "gray blueberry",
    "gray broccoli",
    "gray brussels sprout",
    "gray cabbage",
    "gray cantaloupe",
    "gray carrot",
    "gray cat",
    "gray cauliflower",
    "gray celery",
    "gray cheetah",
    "gray cherry",
    "gray chimp",
    "gray coconut",
    "gray corn",
    "gray cow",
    "gray cranberry",
    "gray cucumber",
    "gray date",
    "gray deer",
    "gray dog",
    "gray dolphin",
    "gray dragon fruit",
    "gray duck",
    "gray eagle",
    "gray eggplant",
    "gray elephant",
    "gray fig",
    "gray flamingo",
    "gray fox",
    "gray frog",
    "gray garlic",
    "gray ginger",
    "gray giraffe",
    "gray gorilla",
    "gray grapefruit",
    "gray grapes",
    "gray green bean",
    "gray guava",
    "gray hippo",
    "gray honeydew",
    "gray horse",
    "gray hummingbird",
    "gray kangaroo",
    "gray kiwi",
    "gray koala",
    "gray leek",
    "gray lemon",
    "gray lettuce",
    "gray lion",
    "gray mango",
    "gray mushroom",
    "gray onion",
    "gray orange",
    "gray orangutan",
    "gray owl",
    "gray panda",
    "gray papaya",
    "gray parrot",
    "gray passion fruit",
    "gray pea",
    "gray peach",
    "gray peacock",
    "gray pelican",
    "gray penguin",
    "gray persimmon",
    "gray pig",
    "gray pineapple",
    "gray plum",
    "gray polar bear",
    "gray pomegranate",
    "gray potato",
    "gray pumpkin",
    "gray rabbit",
    "gray radish",
    "gray raspberry",
    "gray rhino",
    "gray rooster",
    "gray sheep",
    "gray spinach",
    "gray squash",
    "gray strawberry",
    "gray swan",
    "gray sweet potato",
    "gray tiger",
    "gray tomato",
    "gray turnip",
    "gray watermelon",
    "gray wolf",
    "gray zebra",
    "gray zucchini",
    "green apple",
    "green apricot",
    "green artichoke",
    "green asparagus",
    "green banana",
    "green bean",
    "green bear",
    "green beet",
    "green bell pepper",
    "green bird",
    "green blackberry",
    "green blueberry",
    "green broccoli",
    "green brussels sprout",
    "green cabbage",
    "green cantaloupe",
    "green carrot",
    "green cat",
    "green cauliflower",
    "green celery",
    "green cheetah",
    "green cherry",
    "green chimp",
    "green coconut",
    "green corn",
    "green cow",
    "green cranberry",
    "green cucumber",
    "green date",
    "green deer",
    "green dog",
    "green dolphin",
    "green dragon fruit",
    "green duck",
    "green eagle",
    "green eggplant",
    "green elephant",
    "green fig",
    "green flamingo",
    "green fox",
    "green frog",
    "green garlic",
    "green ginger",
    "green giraffe",
    "green gorilla",
    "green grapefruit",
    "green grapes",
    "green green bean",
    "green guava",
    "green hippo",
    "green honeydew",
    "green horse",
    "green hummingbird",
    "green kangaroo",
    "green kiwi",
    "green koala",
    "green leek",
    "green lemon",
    "green lettuce",
    "green lion",
    "green mango",
    "green mushroom",
    "green onion",
    "green orange",
    "green orangutan",
    "green owl",
    "green panda",
    "green papaya",
    "green parrot",
    "green passion fruit",
    "green pea",
    "green peach",
    "green peacock",
    "green pelican",
    "green penguin",
    "green persimmon",
    "green pig",
    "green pineapple",
    "green plum",
    "green polar bear",
    "green pomegranate",
    "green potato",
    "green pumpkin",
    "green rabbit",
    "green radish",
    "green raspberry",
    "green rhino",
    "green rooster",
    "green sheep",
    "green spinach",
    "green squash",
    "green strawberry",
    "green swan",
    "green sweet potato",
    "green tiger",
    "green tomato",
    "green turnip",
    "green watermelon",
    "green wolf",
    "green zebra",
    "green zucchini",
    "grill",
    "guava",
    "guitar",
    "hamburger",
    "hammer",
    "hammock",
    "harp",
    "hat",
    "headphone",
    "headphones",
    "heart monitor",
    "helicopter",
    "high chair",
    "hiking boot",
    "hippo",
    "hockey stick",
    "honeydew",
    "hoodie",
    "horse",
    "hot dog",
    "hourglass",
    "hummingbird",
    "ice cream",
    "ice maker",
    "icicle",
    "igloo",
    "iguana",
    "indigo apple",
    "indigo apricot",
    "indigo artichoke",
    "indigo asparagus",
    "indigo banana",
    "indigo bear",
    "indigo beet",
    "indigo bell pepper",
    "indigo bird",
    "indigo blackberry",
    "indigo blueberry",
    "indigo broccoli",
    "indigo brussels sprout",
    "indigo cabbage",
    "indigo cantaloupe",
    "indigo carrot",
    "indigo cat",
    "indigo cauliflower",
    "indigo celery",
    "indigo cheetah",
    "indigo cherry",
    "indigo chimp",
    "indigo coconut",
    "indigo corn",
    "indigo cow",
    "indigo cranberry",
    "indigo cucumber",
    "indigo date",
    "indigo deer",
    "indigo dog",
    "indigo dolphin",
    "indigo dragon fruit",
    "indigo duck",
    "indigo eagle",
    "indigo eggplant",
    "indigo elephant",
    "indigo fig",
    "indigo flamingo",
    "indigo fox",
    "indigo frog",
    "indigo garlic",
    "indigo ginger",
    "indigo giraffe",
    "indigo gorilla",
    "indigo grapefruit",
    "indigo grapes",
    "indigo green bean",
    "indigo guava",
    "indigo hippo",
    "indigo honeydew",
    "indigo horse",
    "indigo hummingbird",
    "indigo kangaroo",
    "indigo kiwi",
    "indigo koala",
    "indigo leek",
    "indigo lemon",
    "indigo lettuce",
    "indigo lion",
    "indigo mango",
    "indigo mushroom",
    "indigo onion",
    "indigo orange",
    "indigo orangutan",
    "indigo owl",
    "indigo panda",
    "indigo papaya",
    "indigo parrot",
    "indigo passion fruit",
    "indigo pea",
    "indigo peach",
    "indigo peacock",
    "indigo pelican",
    "indigo penguin",
    "indigo persimmon",
    "indigo pig",
    "indigo pineapple",
    "indigo plum",
    "indigo polar bear",
    "indigo pomegranate",
    "indigo potato",
    "indigo pumpkin",
    "indigo rabbit",
    "indigo radish",
    "indigo raspberry",
    "indigo rhino",
    "indigo rooster",
    "indigo sheep",
    "indigo spinach",
    "indigo squash",
    "indigo strawberry",
    "indigo swan",
    "indigo sweet potato",
    "indigo tiger",
    "indigo tomato",
    "indigo turnip",
    "indigo watermelon",
    "indigo wolf",
    "indigo zebra",
    "indigo zucchini",
    "island",
    "ivory apple",
    "ivory apricot",
    "ivory artichoke",
    "ivory asparagus",
    "ivory banana",
    "ivory bear",
    "ivory beet",
    "ivory bell pepper",
    "ivory bird",
    "ivory blackberry",
    "ivory blueberry",
    "ivory broccoli",
    "ivory brussels sprout",
    "ivory cabbage",
    "ivory cantaloupe",
    "ivory carrot",
    "ivory cat",
    "ivory cauliflower",
    "ivory celery",
    "ivory cheetah",
    "ivory cherry",
    "ivory chimp",
    "ivory coconut",
    "ivory corn",
    "ivory cow",
    "ivory cranberry",
    "ivory cucumber",
    "ivory date",
    "ivory deer",
    "ivory dog",
    "ivory dolphin",
    "ivory dragon fruit",
    "ivory duck",
    "ivory eagle",
    "ivory eggplant",
    "ivory elephant",
    "ivory fig",
    "ivory flamingo",
    "ivory fox",
    "ivory frog",
    "ivory garlic",
    "ivory ginger",
    "ivory giraffe",
    "ivory gorilla",
    "ivory grapefruit",
    "ivory grapes",
    "ivory green bean",
    "ivory guava",
    "ivory hippo",
    "ivory honeydew",
    "ivory horse",
    "ivory hummingbird",
    "ivory kangaroo",
    "ivory kiwi",
    "ivory koala",
    "ivory leek",
    "ivory lemon",
    "ivory lettuce",
    "ivory lion",
    "ivory mango",
    "ivory mushroom",
    "ivory onion",
    "ivory orange",
    "ivory orangutan",
    "ivory owl",
    "ivory panda",
    "ivory papaya",
    "ivory parrot",
    "ivory passion fruit",
    "ivory pea",
    "ivory peach",
    "ivory peacock",
    "ivory pelican",
    "ivory penguin",
    "ivory persimmon",
    "ivory pig",
    "ivory pineapple",
    "ivory plum",
    "ivory polar bear",
    "ivory pomegranate",
    "ivory potato",
    "ivory pumpkin",
    "ivory rabbit",
    "ivory radish",
    "ivory raspberry",
    "ivory rhino",
    "ivory rooster",
    "ivory sheep",
    "ivory spinach",
    "ivory squash",
    "ivory strawberry",
    "ivory swan",
    "ivory sweet potato",
    "ivory tiger",
    "ivory tomato",
    "ivory turnip",
    "ivory watermelon",
    "ivory wolf",
    "ivory zebra",
    "ivory zucchini",
    "jack o lantern",
    "jacket",
    "jeans",
    "jellyfish",
    "jet ski",
    "jigsaw puzzle",
    "juicer",
    "kangaroo",
    "kayak",
    "kettle",
    "keyboard",
    "kite",
    "kiwi",
    "knife",
    "koala",
    "ladder",
    "ladybug",
    "lake",
    "lamp",
    "lantern",
    "laptop",
    "large apple",
    "large apricot",
    "large asparagus",
    "large banana",
    "large bell pepper",
    "large blackberry",
    "large blueberry",
    "large broccoli",
    "large cabbage",
    "large cantaloupe",
    "large carrot",
    "large cauliflower",
    "large celery",
    "large cherry",
    "large coconut",
    "large corn",
    "large cranberry",
    "large cucumber",
    "large date",
    "large dragon fruit",
    "large eggplant",
    "large fig",
    "large grapefruit",
    "large grapes",
    "large guava",
    "large honeydew",
    "large kiwi",
    "large lemon",
    "large lettuce",
    "large mango",
    "large mushroom",
    "large onion",
    "large orange",
    "large papaya",
    "large passion fruit",
    "large peach",
    "large persimmon",
    "large pineapple",
    "large plum",
    "large pomegranate",
    "large potato",
    "large pumpkin",
    "large radish",
    "large raspberry",
    "large spinach",
    "large squash",
    "large strawberry",
    "large tomato",
    "large watermelon",
    "large zucchini",
    "lawn mower",
    "leather bowl",
    "leather box",
    "leather cabinet",
    "leather chair",
    "leather cup",
    "leather door",
    "leather fork",
    "leather frame",
    "leather plate",
    "leather sculpture",
    "leather spoon",
    "leather statue",
    "leather table",
    "leather vase",
    "leek",
    "lego brick",
    "lemon",
    "lettuce",
    "lighthouse",
    "lily",
    "limousine",
    "lion",
    "lizard",
    "macaron",
    "magenta apple",
    "magenta apricot",
    "magenta artichoke",
    "magenta asparagus",
    "magenta banana",
    "magenta bear",
    "magenta beet",
    "magenta bell pepper",
    "magenta bird",
    "magenta blackberry",
    "magenta blueberry",
    "magenta broccoli",
    "magenta brussels sprout",
    "magenta cabbage",
    "magenta cantaloupe",
    "magenta carrot",
    "magenta cat",
    "magenta cauliflower",
    "magenta celery",
    "magenta cheetah",
    "magenta cherry",
    "magenta chimp",
    "magenta coconut",
    "magenta corn",
    "magenta cow",
    "magenta cranberry",
    "magenta cucumber",
    "magenta date",
    "magenta deer",
    "magenta dog",
    "magenta dolphin",
    "magenta dragon fruit",
    "magenta duck",
    "magenta eagle",
    "magenta eggplant",
    "magenta elephant",
    "magenta fig",
    "magenta flamingo",
    "magenta fox",
    "magenta frog",
    "magenta garlic",
    "magenta ginger",
    "magenta giraffe",
    "magenta gorilla",
    "magenta grapefruit",
    "magenta grapes",
    "magenta green bean",
    "magenta guava",
    "magenta hippo",
    "magenta honeydew",
    "magenta horse",
    "magenta hummingbird",
    "magenta kangaroo",
    "magenta kiwi",
    "magenta koala",
    "magenta leek",
    "magenta lemon",
    "magenta lettuce",
    "magenta lion",
    "magenta mango",
    "magenta mushroom",
    "magenta onion",
    "magenta orange",
    "magenta orangutan",
    "magenta owl",
    "magenta panda",
    "magenta papaya",
    "magenta parrot",
    "magenta passion fruit",
    "magenta pea",
    "magenta peach",
    "magenta peacock",
    "magenta pelican",
    "magenta penguin",
    "magenta persimmon",
    "magenta pig",
    "magenta pineapple",
    "magenta plum",
    "magenta polar bear",
    "magenta pomegranate",
    "magenta potato",
    "magenta pumpkin",
    "magenta rabbit",
    "magenta radish",
    "magenta raspberry",
    "magenta rhino",
    "magenta rooster",
    "magenta sheep",
    "magenta spinach",
    "magenta squash",
    "magenta strawberry",
    "magenta swan",
    "magenta sweet potato",
    "magenta tiger",
    "magenta tomato",
    "magenta turnip",
    "magenta watermelon",
    "magenta wolf",
    "magenta zebra",
    "magenta zucchini",
    "magnifying glass",
    "mahjong tile",
    "mango",
    "maple tree",
    "marble bowl",
    "marble box",
    "marble cabinet",
    "marble chair",
    "marble cup",
    "marble door",
    "marble fork",
    "marble frame",
    "marble plate",
    "marble sculpture",
    "marble spoon",
    "marble statue",
    "marble table",
    "marble vase",
    "marbles",
    "maroon apple",
    "maroon apricot",
    "maroon artichoke",
    "maroon asparagus",
    "maroon banana",
    "maroon bear",
    "maroon beet",
    "maroon bell pepper",
    "maroon bird",
    "maroon blackberry",
    "maroon blueberry",
    "maroon broccoli",
    "maroon brussels sprout",
    "maroon cabbage",
    "maroon cantaloupe",
    "maroon carrot",
    "maroon cat",
    "maroon cauliflower",
    "maroon celery",
    "maroon cheetah",
    "maroon cherry",
    "maroon chimp",
    "maroon coconut",
    "maroon corn",
    "maroon cow",
    "maroon cranberry",
    "maroon cucumber",
    "maroon date",
    "maroon deer",
    "maroon dog",
    "maroon dolphin",
    "maroon dragon fruit",
    "maroon duck",
    "maroon eagle",
    "maroon eggplant",
    "maroon elephant",
    "maroon fig",
    "maroon flamingo",
    "maroon fox",
    "maroon frog",
    "maroon garlic",
    "maroon ginger",
    "maroon giraffe",
    "maroon gorilla",
    "maroon grapefruit",
    "maroon grapes",
    "maroon green bean",
    "maroon guava",
    "maroon hippo",
    "maroon honeydew",
    "maroon horse",
    "maroon hummingbird",
    "maroon kangaroo",
    "maroon kiwi",
    "maroon koala",
    "maroon leek",
    "maroon lemon",
    "maroon lettuce",
    "maroon lion",
    "maroon mango",
    "maroon mushroom",
    "maroon onion",
    "maroon orange",
    "maroon orangutan",
    "maroon owl",
    "maroon panda",
    "maroon papaya",
    "maroon parrot",
    "maroon passion fruit",
    "maroon pea",
    "maroon peach",
    "maroon peacock",
    "maroon pelican",
    "maroon penguin",
    "maroon persimmon",
    "maroon pig",
    "maroon pineapple",
    "maroon plum",
    "maroon polar bear",
    "maroon pomegranate",
    "maroon potato",
    "maroon pumpkin",
    "maroon rabbit",
    "maroon radish",
    "maroon raspberry",
    "maroon rhino",
    "maroon rooster",
    "maroon sheep",
    "maroon spinach",
    "maroon squash",
    "maroon strawberry",
    "maroon swan",
    "maroon sweet potato",
    "maroon tiger",
    "maroon tomato",
    "maroon turnip",
    "maroon watermelon",
    "maroon wolf",
    "maroon zebra",
    "maroon zucchini",
    "medal",
    "metal bowl",
    "metal box",
    "metal cabinet",
    "metal chair",
    "metal cup",
    "metal door",
    "metal fork",
    "metal frame",
    "metal plate",
    "metal sculpture",
    "metal spoon",
    "metal statue",
    "metal table",
    "metal vase",
    "metronome",
    "microphone",
    "microwave",
    "miniature apple",
    "miniature apricot",
    "miniature asparagus",
    "miniature banana",
    "miniature bell pepper",
    "miniature blackberry",
    "miniature blueberry",
    "miniature broccoli",
    "miniature cabbage",
    "miniature cantaloupe",
    "miniature carrot",
    "miniature cauliflower",
    "miniature celery",
    "miniature cherry",
    "miniature coconut",
    "miniature corn",
    "miniature cranberry",
    "miniature cucumber",
    "miniature date",
    "miniature dragon fruit",
    "miniature eggplant",
    "miniature fig",
    "miniature grapefruit",
    "miniature grapes",
    "miniature guava",
    "miniature honeydew",
    "miniature kiwi",
    "miniature lemon",
    "miniature lettuce",
    "miniature mango",
    "miniature mushroom",
    "miniature onion",
    "miniature orange",
    "miniature papaya",
    "miniature passion fruit",
    "miniature peach",
    "miniature persimmon",
    "miniature pineapple",
    "miniature plum",
    "miniature pomegranate",
    "miniature potato",
    "miniature pumpkin",
    "miniature radish",
    "miniature raspberry",
    "miniature spinach",
    "miniature squash",
    "miniature strawberry",
    "miniature tomato",
    "miniature watermelon",
    "miniature zucchini",
    "mirror",
    "mixer",
    "mobile",
    "monitor",
    "moon",
    "mop",
    "mosaic",
    "mosque",
    "moss",
    "motorcycle",
    "mountain",
    "mouse",
    "mug",
    "mushroom",
    "music stand",
    "nacho",
    "navy apple",
    "navy apricot",
    "navy artichoke",
    "navy asparagus",
    "navy banana",
    "navy bear",
    "navy beet",
    "navy bell pepper",
    "navy bird",
    "navy blackberry",
    "navy blueberry",
    "navy broccoli",
    "navy brussels sprout",
    "navy cabbage",
    "navy cantaloupe",
    "navy carrot",
    "navy cat",
    "navy cauliflower",
    "navy celery",
    "navy cheetah",
    "navy cherry",
    "navy chimp",
    "navy coconut",
    "navy corn",
    "navy cow",
    "navy cranberry",
    "navy cucumber",
    "navy date",
    "navy deer",
    "navy dog",
    "navy dolphin",
    "navy dragon fruit",
    "navy duck",
    "navy eagle",
    "navy eggplant",
    "navy elephant",
    "navy fig",
    "navy flamingo",
    "navy fox",
    "navy frog",
    "navy garlic",
    "navy ginger",
    "navy giraffe",
    "navy gorilla",
    "navy grapefruit",
    "navy grapes",
    "navy green bean",
    "navy guava",
    "navy hippo",
    "navy honeydew",
    "navy horse",
    "navy hummingbird",
    "navy kangaroo",
    "navy kiwi",
    "navy koala",
    "navy leek",
    "navy lemon",
    "navy lettuce",
    "navy lion",
    "navy mango",
    "navy mushroom",
    "navy onion",
    "navy orange",
    "navy orangutan",
    "navy owl",
    "navy panda",
    "navy papaya",
    "navy parrot",
    "navy passion fruit",
    "navy pea",
    "navy peach",
    "navy peacock",
    "navy pelican",
    "navy penguin",
    "navy persimmon",
    "navy pig",
    "navy pineapple",
    "navy plum",
    "navy polar bear",
    "navy pomegranate",
    "navy potato",
    "navy pumpkin",
    "navy rabbit",
    "navy radish",
    "navy raspberry",
    "navy rhino",
    "navy rooster",
    "navy sheep",
    "navy spinach",
    "navy squash",
    "navy strawberry",
    "navy swan",
    "navy sweet potato",
    "navy tiger",
    "navy tomato",
    "navy turnip",
    "navy watermelon",
    "navy wolf",
    "navy zebra",
    "navy zucchini",
    "necklace",
    "nightstand",
    "notebook",
    "oak tree",
    "ocean",
    "octopus",
    "oil painting",
    "olive apple",
    "olive apricot",
    "olive artichoke",
    "olive asparagus",
    "olive banana",
    "olive bear",
    "olive beet",
    "olive bell pepper",
    "olive bird",
    "olive blackberry",
    "olive blueberry",
    "olive broccoli",
    "olive brussels sprout",
    "olive cabbage",
    "olive cantaloupe",
    "olive carrot",
    "olive cat",
    "olive cauliflower",
    "olive celery",
    "olive cheetah",
    "olive cherry",
    "olive chimp",
    "olive coconut",
    "olive corn",
    "olive cow",
    "olive cranberry",
    "olive cucumber",
    "olive date",
    "olive deer",
    "olive dog",
    "olive dolphin",
    "olive dragon fruit",
    "olive duck",
    "olive eagle",
    "olive eggplant",
    "olive elephant",
    "olive fig",
    "olive flamingo",
    "olive fox",
    "olive frog",
    "olive garlic",
    "olive ginger",
    "olive giraffe",
    "olive gorilla",
    "olive grapefruit",
    "olive grapes",
    "olive green bean",
    "olive guava",
    "olive hippo",
    "olive honeydew",
    "olive horse",
    "olive hummingbird",
    "olive kangaroo",
    "olive kiwi",
    "olive koala",
    "olive leek",
    "olive lemon",
    "olive lettuce",
    "olive lion",
    "olive mango",
    "olive mushroom",
    "olive onion",
    "olive orange",
    "olive orangutan",
    "olive owl",
    "olive panda",
    "olive papaya",
    "olive parrot",
    "olive passion fruit",
    "olive pea",
    "olive peach",
    "olive peacock",
    "olive pelican",
    "olive penguin",
    "olive persimmon",
    "olive pig",
    "olive pineapple",
    "olive plum",
    "olive polar bear",
    "olive pomegranate",
    "olive potato",
    "olive pumpkin",
    "olive rabbit",
    "olive radish",
    "olive raspberry",
    "olive rhino",
    "olive rooster",
    "olive sheep",
    "olive spinach",
    "olive squash",
    "olive strawberry",
    "olive swan",
    "olive sweet potato",
    "olive tiger",
    "olive tomato",
    "olive turnip",
    "olive watermelon",
    "olive wolf",
    "olive zebra",
    "olive zucchini",
    "omelette",
    "onion",
    "opal",
    "orange",
    "orange apple",
    "orange apricot",
    "orange artichoke",
    "orange asparagus",
    "orange banana",
    "orange bear",
    "orange beet",
    "orange bell pepper",
    "orange bird",
    "orange blackberry",
    "orange blueberry",
    "orange broccoli",
    "orange brussels sprout",
    "orange cabbage",
    "orange cantaloupe",
    "orange carrot",
    "orange cat",
    "orange cauliflower",
    "orange celery",
    "orange cheetah",
    "orange cherry",
    "orange chimp",
    "orange coconut",
    "orange corn",
    "orange cow",
    "orange cranberry",
    "orange cucumber",
    "orange date",
    "orange deer",
    "orange dog",
    "orange dolphin",
    "orange dragon fruit",
    "orange duck",
    "orange eagle",
    "orange eggplant",
    "orange elephant",
    "orange fig",
    "orange flamingo",
    "orange fox",
    "orange frog",
    "orange garlic",
    "orange ginger",
    "orange giraffe",
    "orange gorilla",
    "orange grapefruit",
    "orange grapes",
    "orange green bean",
    "orange guava",
    "orange hippo",
    "orange honeydew",
    "orange horse",
    "orange hummingbird",
    "orange kangaroo",
    "orange kiwi",
    "orange koala",
    "orange leek",
    "orange lemon",
    "orange lettuce",
    "orange lion",
    "orange mango",
    "orange mushroom",
    "orange onion",
    "orange orange",
    "orange orangutan",
    "orange owl",
    "orange panda",
    "orange papaya",
    "orange parrot",
    "orange passion fruit",
    "orange pea",
    "orange peach",
    "orange peacock",
    "orange pelican",
    "orange penguin",
    "orange persimmon",
    "orange pig",
    "orange pineapple",
    "orange plum",
    "orange polar bear",
    "orange pomegranate",
    "orange potato",
    "orange pumpkin",
    "orange rabbit",
    "orange radish",
    "orange raspberry",
    "orange rhino",
    "orange rooster",
    "orange sheep",
    "orange spinach",
    "orange squash",
    "orange strawberry",
    "orange swan",
    "orange sweet potato",
    "orange tiger",
    "orange tomato",
    "orange turnip",
    "orange watermelon",
    "orange wolf",
    "orange zebra",
    "orange zucchini",
    "orangutan",
    "orchid",
    "otter",
    "oven",
    "owl",
    "oxygen tank",
    "pacifier",
    "pagoda",
    "paintbrush",
    "palette",
    "palm tree",
    "pan",
    "pancake",
    "panda",
    "papaya",
    "paper clip",
    "parrot",
    "party hat",
    "passion fruit",
    "pasta",
    "pea",
    "peach",
    "peacock",
    "pearl",
    "pebble",
    "pelican",
    "pen",
    "pencil holder",
    "penguin",
    "persimmon",
    "piano",
    "picture frame",
    "pie",
    "pig",
    "pill bottle",
    "pillow",
    "pine tree",
    "pineapple",
    "pink apple",
    "pink apricot",
    "pink artichoke",
    "pink asparagus",
    "pink banana",
    "pink bear",
    "pink beet",
    "pink bell pepper",
    "pink bird",
    "pink blackberry",
    "pink blueberry",
    "pink broccoli",
    "pink brussels sprout",
    "pink cabbage",
    "pink cantaloupe",
    "pink carrot",
    "pink cat",
    "pink cauliflower",
    "pink celery",
    "pink cheetah",
    "pink cherry",
    "pink chimp",
    "pink coconut",
    "pink corn",
    "pink cow",
    "pink cranberry",
    "pink cucumber",
    "pink date",
    "pink deer",
    "pink dog",
    "pink dolphin",
    "pink dragon fruit",
    "pink duck",
    "pink eagle",
    "pink eggplant",
    "pink elephant",
    "pink fig",
    "pink flamingo",
    "pink fox",
    "pink frog",
    "pink garlic",
    "pink ginger",
    "pink giraffe",
    "pink gorilla",
    "pink grapefruit",
    "pink grapes",
    "pink green bean",
    "pink guava",
    "pink hippo",
    "pink honeydew",
    "pink horse",
    "pink hummingbird",
    "pink kangaroo",
    "pink kiwi",
    "pink koala",
    "pink leek",
    "pink lemon",
    "pink lettuce",
    "pink lion",
    "pink mango",
    "pink mushroom",
    "pink onion",
    "pink orange",
    "pink orangutan",
    "pink owl",
    "pink panda",
    "pink papaya",
    "pink parrot",
    "pink passion fruit",
    "pink pea",
    "pink peach",
    "pink peacock",
    "pink pelican",
    "pink penguin",
    "pink persimmon",
    "pink pig",
    "pink pineapple",
    "pink plum",
    "pink polar bear",
    "pink pomegranate",
    "pink potato",
    "pink pumpkin",
    "pink rabbit",
    "pink radish",
    "pink raspberry",
    "pink rhino",
    "pink rooster",
    "pink sheep",
    "pink spinach",
    "pink squash",
    "pink strawberry",
    "pink swan",
    "pink sweet potato",
    "pink tiger",
    "pink tomato",
    "pink turnip",
    "pink watermelon",
    "pink wolf",
    "pink zebra",
    "pink zucchini",
    "pizza",
    "plant",
    "plastic bowl",
    "plastic box",
    "plastic cabinet",
    "plastic chair",
    "plastic cup",
    "plastic door",
    "plastic fork",
    "plastic frame",
    "plastic plate",
    "plastic sculpture",
    "plastic spoon",
    "plastic statue",
    "plastic table",
    "plastic vase",
    "playing card",
    "pliers",
    "plum",
    "poker chip",
    "polar bear",
    "pomegranate",
    "porcelain bowl",
    "porcelain box",
    "porcelain cabinet",
    "porcelain chair",
    "porcelain cup",
    "porcelain door",
    "porcelain fork",
    "porcelain frame",
    "porcelain plate",
    "porcelain sculpture",
    "porcelain spoon",
    "porcelain statue",
    "porcelain table",
    "porcelain vase",
    "pot",
    "potato",
    "pottery",
    "pressure cooker",
    "pretzel",
    "printer",
    "projector",
    "pumpkin",
    "purple apple",
    "purple apricot",
    "purple artichoke",
    "purple asparagus",
    "purple banana",
    "purple bear",
    "purple beet",
    "purple bell pepper",
    "purple bird",
    "purple blackberry",
    "purple blueberry",
    "purple broccoli",
    "purple brussels sprout",
    "purple cabbage",
    "purple cantaloupe",
    "purple carrot",
    "purple cat",
    "purple cauliflower",
    "purple celery",
    "purple cheetah",
    "purple cherry",
    "purple chimp",
    "purple coconut",
    "purple corn",
    "purple cow",
    "purple cranberry",
    "purple cucumber",
    "purple date",
    "purple deer",
    "purple dog",
    "purple dolphin",
    "purple dragon fruit",
    "purple duck",
    "purple eagle",
    "purple eggplant",
    "purple elephant",
    "purple fig",
    "purple flamingo",
    "purple fox",
    "purple frog",
    "purple garlic",
    "purple ginger",
    "purple giraffe",
    "purple gorilla",
    "purple grapefruit",
    "purple grapes",
    "purple green bean",
    "purple guava",
    "purple hippo",
    "purple honeydew",
    "purple horse",
    "purple hummingbird",
    "purple kangaroo",
    "purple kiwi",
    "purple koala",
    "purple leek",
    "purple lemon",
    "purple lettuce",
    "purple lion",
    "purple mango",
    "purple mushroom",
    "purple onion",
    "purple orange",
    "purple orangutan",
    "purple owl",
    "purple panda",
    "purple papaya",
    "purple parrot",
    "purple passion fruit",
    "purple pea",
    "purple peach",
    "purple peacock",
    "purple pelican",
    "purple penguin",
    "purple persimmon",
    "purple pig",
    "purple pineapple",
    "purple plum",
    "purple polar bear",
    "purple pomegranate",
    "purple potato",
    "purple pumpkin",
    "purple rabbit",
    "purple radish",
    "purple raspberry",
    "purple rhino",
    "purple rooster",
    "purple sheep",
    "purple spinach",
    "purple squash",
    "purple strawberry",
    "purple swan",
    "purple sweet potato",
    "purple tiger",
    "purple tomato",
    "purple turnip",
    "purple watermelon",
    "purple wolf",
    "purple zebra",
    "purple zucchini",
    "puzzle",
    "puzzle piece",
    "rabbit",
    "radish",
    "rainbow",
    "rake",
    "ramen",
    "raspberry",
    "rattle",
    "recycling bin",
    "red apple",
    "red apricot",
    "red artichoke",
    "red asparagus",
    "red banana",
    "red bear",
    "red beet",
    "red bell pepper",
    "red bird",
    "red blackberry",
    "red blueberry",
    "red broccoli",
    "red brussels sprout",
    "red cabbage",
    "red cantaloupe",
    "red carrot",
    "red cat",
    "red cauliflower",
    "red celery",
    "red cheetah",
    "red cherry",
    "red chimp",
    "red coconut",
    "red corn",
    "red cow",
    "red cranberry",
    "red cucumber",
    "red date",
    "red deer",
    "red dog",
    "red dolphin",
    "red dragon fruit",
    "red duck",
    "red eagle",
    "red eggplant",
    "red elephant",
    "red fig",
    "red flamingo",
    "red fox",
    "red frog",
    "red garlic",
    "red ginger",
    "red giraffe",
    "red gorilla",
    "red grapefruit",
    "red grapes",
    "red green bean",
    "red guava",
    "red hippo",
    "red honeydew",
    "red horse",
    "red hummingbird",
    "red kangaroo",
    "red kiwi",
    "red koala",
    "red leek",
    "red lemon",
    "red lettuce",
    "red lion",
    "red mango",
    "red mushroom",
    "red onion",
    "red orange",
    "red orangutan",
    "red owl",
    "red panda",
    "red papaya",
    "red parrot",
    "red passion fruit",
    "red pea",
    "red peach",
    "red peacock",
    "red pelican",
    "red penguin",
    "red persimmon",
    "red pig",
    "red pineapple",
    "red plum",
    "red polar bear",
    "red pomegranate",
    "red potato",
    "red pumpkin",
    "red rabbit",
    "red radish",
    "red raspberry",
    "red rhino",
    "red rooster",
    "red sheep",
    "red spinach",
    "red squash",
    "red strawberry",
    "red swan",
    "red sweet potato",
    "red tiger",
    "red tomato",
    "red turnip",
    "red watermelon",
    "red wolf",
    "red zebra",
    "red zucchini",
    "redwood tree",
    "refrigerator",
    "rhino",
    "rice cooker",
    "ring",
    "river",
    "rocket",
    "rocking horse",
    "rooster",
    "rose",
    "router",
    "rubber bowl",
    "rubber box",
    "rubber cabinet",
    "rubber chair",
    "rubber cup",
    "rubber door",
    "rubber fork",
    "rubber frame",
    "rubber plate",
    "rubber sculpture",
    "rubber spoon",
    "rubber statue",
    "rubber table",
    "rubber vase",
    "rubik cube",
    "ruby",
    "rug",
    "salad",
    "sandal",
    "sapphire",
    "saw",
    "saxophone",
    "scarf",
    "scissors",
    "scooter",
    "screwdriver",
    "sculpture",
    "seagull",
    "seal",
    "seashell",
    "shark",
    "sheep",
    "sheet music",
    "shirt",
    "shovel",
    "silk bowl",
    "silk box",
    "silk cabinet",
    "silk chair",
    "silk cup",
    "silk door",
    "silk fork",
    "silk frame",
    "silk plate",
    "silk sculpture",
    "silk spoon",
    "silk statue",
    "silk table",
    "silk vase",
    "silver apple",
    "silver apricot",
    "silver artichoke",
    "silver asparagus",
    "silver banana",
    "silver bear",
    "silver beet",
    "silver bell pepper",
    "silver bird",
    "silver blackberry",
    "silver blueberry",
    "silver broccoli",
    "silver brussels sprout",
    "silver cabbage",
    "silver cantaloupe",
    "silver carrot",
    "silver cat",
    "silver cauliflower",
    "silver celery",
    "silver cheetah",
    "silver cherry",
    "silver chimp",
    "silver coconut",
    "silver corn",
    "silver cow",
    "silver cranberry",
    "silver cucumber",
    "silver date",
    "silver deer",
    "silver dog",
    "silver dolphin",
    "silver dragon fruit",
    "silver duck",
    "silver eagle",
    "silver eggplant",
    "silver elephant",
    "silver fig",
    "silver flamingo",
    "silver fox",
    "silver frog",
    "silver garlic",
    "silver ginger",
    "silver giraffe",
    "silver gorilla",
    "silver grapefruit",
    "silver grapes",
    "silver green bean",
    "silver guava",
    "silver hippo",
    "silver honeydew",
    "silver horse",
    "silver hummingbird",
    "silver kangaroo",
    "silver kiwi",
    "silver koala",
    "silver leek",
    "silver lemon",
    "silver lettuce",
    "silver lion",
    "silver mango",
    "silver mushroom",
    "silver onion",
    "silver orange",
    "silver orangutan",
    "silver owl",
    "silver panda",
    "silver papaya",
    "silver parrot",
    "silver passion fruit",
    "silver pea",
    "silver peach",
    "silver peacock",
    "silver pelican",
    "silver penguin",
    "silver persimmon",
    "silver pig",
    "silver pineapple",
    "silver plum",
    "silver polar bear",
    "silver pomegranate",
    "silver potato",
    "silver pumpkin",
    "silver rabbit",
    "silver radish",
    "silver raspberry",
    "silver rhino",
    "silver rooster",
    "silver sheep",
    "silver spinach",
    "silver squash",
    "silver strawberry",
    "silver swan",
    "silver sweet potato",
    "silver tiger",
    "silver tomato",
    "silver turnip",
    "silver watermelon",
    "silver wolf",
    "silver zebra",
    "silver zucchini",
    "skateboard",
    "skyscraper",
    "sleeping bag",
    "slow cooker",
    "small apple",
    "small apricot",
    "small asparagus",
    "small banana",
    "small bell pepper",
    "small blackberry",
    "small blueberry",
    "small broccoli",
    "small cabbage",
    "small cantaloupe",
    "small carrot",
    "small cauliflower",
    "small celery",
    "small cherry",
    "small coconut",
    "small corn",
    "small cranberry",
    "small cucumber",
    "small date",
    "small dragon fruit",
    "small eggplant",
    "small fig",
    "small grapefruit",
    "small grapes",
    "small guava",
    "small honeydew",
    "small kiwi",
    "small lemon",
    "small lettuce",
    "small mango",
    "small mushroom",
    "small onion",
    "small orange",
    "small papaya",
    "small passion fruit",
    "small peach",
    "small persimmon",
    "small pineapple",
    "small plum",
    "small pomegranate",
    "small potato",
    "small pumpkin",
    "small radish",
    "small raspberry",
    "small spinach",
    "small squash",
    "small strawberry",
    "small tomato",
    "small watermelon",
    "small zucchini",
    "smartphone",
    "smartwatch",
    "snail",
    "snake",
    "sneaker",
    "snowboard",
    "snowflake",
    "snowman",
    "soccer ball",
    "sofa",
    "spaceship",
    "sparrow",
    "spatula",
    "speaker",
    "spinach",
    "spinning top",
    "sponge",
    "spray bottle",
    "spring roll",
    "squash",
    "stamp",
    "stapler",
    "star",
    "starfish",
    "statue",
    "steak",
    "steel bowl",
    "steel box",
    "steel cabinet",
    "steel chair",
    "steel cup",
    "steel door",
    "steel fork",
    "steel frame",
    "steel plate",
    "steel sculpture",
    "steel spoon",
    "steel statue",
    "steel table",
    "steel vase",
    "stethoscope",
    "stone bowl",
    "stone box",
    "stone cabinet",
    "stone chair",
    "stone cup",
    "stone door",
    "stone fork",
    "stone frame",
    "stone plate",
    "stone sculpture",
    "stone spoon",
    "stone statue",
    "stone table",
    "stone vase",
    "stool",
    "stove",
    "strawberry",
    "stuffed bunny",
    "stuffed elephant",
    "submarine",
    "suit",
    "suitcase",
    "sunflower",
    "sunglasses",
    "sunrise",
    "sunset",
    "surfboard",
    "sushi",
    "swan",
    "sweater",
    "sweet potato",
    "syringe",
    "table",
    "tablet",
    "taco",
    "tambourine",
    "tape dispenser",
    "tape measure",
    "tapestry",
    "taxi",
    "teal apple",
    "teal apricot",
    "teal artichoke",
    "teal asparagus",
    "teal banana",
    "teal bear",
    "teal beet",
    "teal bell pepper",
    "teal bird",
    "teal blackberry",
    "teal blueberry",
    "teal broccoli",
    "teal brussels sprout",
    "teal cabbage",
    "teal cantaloupe",
    "teal carrot",
    "teal cat",
    "teal cauliflower",
    "teal celery",
    "teal cheetah",
    "teal cherry",
    "teal chimp",
    "teal coconut",
    "teal corn",
    "teal cow",
    "teal cranberry",
    "teal cucumber",
    "teal date",
    "teal deer",
    "teal dog",
    "teal dolphin",
    "teal dragon fruit",
    "teal duck",
    "teal eagle",
    "teal eggplant",
    "teal elephant",
    "teal fig",
    "teal flamingo",
    "teal fox",
    "teal frog",
    "teal garlic",
    "teal ginger",
    "teal giraffe",
    "teal gorilla",
    "teal grapefruit",
    "teal grapes",
    "teal green bean",
    "teal guava",
    "teal hippo",
    "teal honeydew",
    "teal horse",
    "teal hummingbird",
    "teal kangaroo",
    "teal kiwi",
    "teal koala",
    "teal leek",
    "teal lemon",
    "teal lettuce",
    "teal lion",
    "teal mango",
    "teal mushroom",
    "teal onion",
    "teal orange",
    "teal orangutan",
    "teal owl",
    "teal panda",
    "teal papaya",
    "teal parrot",
    "teal passion fruit",
    "teal pea",
    "teal peach",
    "teal peacock",
    "teal pelican",
    "teal penguin",
    "teal persimmon",
    "teal pig",
    "teal pineapple",
    "teal plum",
    "teal polar bear",
    "teal pomegranate",
    "teal potato",
    "teal pumpkin",
    "teal rabbit",
    "teal radish",
    "teal raspberry",
    "teal rhino",
    "teal rooster",
    "teal sheep",
    "teal spinach",
    "teal squash",
    "teal strawberry",
    "teal swan",
    "teal sweet potato",
    "teal tiger",
    "teal tomato",
    "teal turnip",
    "teal watermelon",
    "teal wolf",
    "teal zebra",
    "teal zucchini",
    "teddy bear",
    "telescope",
    "television",
    "temple",
    "tennis racket",
    "tent",
    "thermometer",
    "tie",
    "tiger",
    "tiny apple",
    "tiny apricot",
    "tiny asparagus",
    "tiny banana",
    "tiny bell pepper",
    "tiny blackberry",
    "tiny blueberry",
    "tiny broccoli",
    "tiny cabbage",
    "tiny cantaloupe",
    "tiny carrot",
    "tiny cauliflower",
    "tiny celery",
    "tiny cherry",
    "tiny coconut",
    "tiny corn",
    "tiny cranberry",
    "tiny cucumber",
    "tiny date",
    "tiny dragon fruit",
    "tiny eggplant",
    "tiny fig",
    "tiny grapefruit",
    "tiny grapes",
    "tiny guava",
    "tiny honeydew",
    "tiny kiwi",
    "tiny lemon",
    "tiny lettuce",
    "tiny mango",
    "tiny mushroom",
    "tiny onion",
    "tiny orange",
    "tiny papaya",
    "tiny passion fruit",
    "tiny peach",
    "tiny persimmon",
    "tiny pineapple",
    "tiny plum",
    "tiny pomegranate",
    "tiny potato",
    "tiny pumpkin",
    "tiny radish",
    "tiny raspberry",
    "tiny spinach",
    "tiny squash",
    "tiny strawberry",
    "tiny tomato",
    "tiny watermelon",
    "tiny zucchini",
    "toaster",
    "tomato",
    "topaz",
    "towel",
    "tower",
    "toy car",
    "toy plane",
    "toy robot",
    "toy soldier",
    "toy train",
    "train",
    "tram",
    "trash can",
    "trombone",
    "trophy",
    "truck",
    "trumpet",
    "tulip",
    "tuning fork",
    "turnip",
    "turntable",
    "turquoise apple",
    "turquoise apricot",
    "turquoise artichoke",
    "turquoise asparagus",
    "turquoise banana",
    "turquoise bear",
    "turquoise beet",
    "turquoise bell pepper",
    "turquoise bird",
    "turquoise blackberry",
    "turquoise blueberry",
    "turquoise broccoli",
    "turquoise brussels sprout",
    "turquoise cabbage",
    "turquoise cantaloupe",
    "turquoise carrot",
    "turquoise cat",
    "turquoise cauliflower",
    "turquoise celery",
    "turquoise cheetah",
    "turquoise cherry",
    "turquoise chimp",
    "turquoise coconut",
    "turquoise corn",
    "turquoise cow",
    "turquoise cranberry",
    "turquoise cucumber",
    "turquoise date",
    "turquoise deer",
    "turquoise dog",
    "turquoise dolphin",
    "turquoise dragon fruit",
    "turquoise duck",
    "turquoise eagle",
    "turquoise eggplant",
    "turquoise elephant",
    "turquoise fig",
    "turquoise flamingo",
    "turquoise fox",
    "turquoise frog",
    "turquoise garlic",
    "turquoise ginger",
    "turquoise giraffe",
    "turquoise gorilla",
    "turquoise grapefruit",
    "turquoise grapes",
    "turquoise green bean",
    "turquoise guava",
    "turquoise hippo",
    "turquoise honeydew",
    "turquoise horse",
    "turquoise hummingbird",
    "turquoise kangaroo",
    "turquoise kiwi",
    "turquoise koala",
    "turquoise leek",
    "turquoise lemon",
    "turquoise lettuce",
    "turquoise lion",
    "turquoise mango",
    "turquoise mushroom",
    "turquoise onion",
    "turquoise orange",
    "turquoise orangutan",
    "turquoise owl",
    "turquoise panda",
    "turquoise papaya",
    "turquoise parrot",
    "turquoise passion fruit",
    "turquoise pea",
    "turquoise peach",
    "turquoise peacock",
    "turquoise pelican",
    "turquoise penguin",
    "turquoise persimmon",
    "turquoise pig",
    "turquoise pineapple",
    "turquoise plum",
    "turquoise polar bear",
    "turquoise pomegranate",
    "turquoise potato",
    "turquoise pumpkin",
    "turquoise rabbit",
    "turquoise radish",
    "turquoise raspberry",
    "turquoise rhino",
    "turquoise rooster",
    "turquoise sheep",
    "turquoise spinach",
    "turquoise squash",
    "turquoise strawberry",
    "turquoise swan",
    "turquoise sweet potato",
    "turquoise tiger",
    "turquoise tomato",
    "turquoise turnip",
    "turquoise watermelon",
    "turquoise wolf",
    "turquoise zebra",
    "turquoise zucchini",
    "turtle",
    "ukulele",
    "umbrella",
    "vacuum cleaner",
    "van",
    "vase",
    "velvet bowl",
    "velvet box",
    "velvet cabinet",
    "velvet chair",
    "velvet cup",
    "velvet door",
    "velvet fork",
    "velvet frame",
    "velvet plate",
    "velvet sculpture",
    "velvet spoon",
    "velvet statue",
    "velvet table",
    "velvet vase",
    "vinyl record",
    "violet apple",
    "violet apricot",
    "violet artichoke",
    "violet asparagus",
    "violet banana",
    "violet bear",
    "violet beet",
    "violet bell pepper",
    "violet bird",
    "violet blackberry",
    "violet blueberry",
    "violet broccoli",
    "violet brussels sprout",
    "violet cabbage",
    "violet cantaloupe",
    "violet carrot",
    "violet cat",
    "violet cauliflower",
    "violet celery",
    "violet cheetah",
    "violet cherry",
    "violet chimp",
    "violet coconut",
    "violet corn",
    "violet cow",
    "violet cranberry",
    "violet cucumber",
    "violet date",
    "violet deer",
    "violet dog",
    "violet dolphin",
    "violet dragon fruit",
    "violet duck",
    "violet eagle",
    "violet eggplant",
    "violet elephant",
    "violet fig",
    "violet flamingo",
    "violet fox",
    "violet frog",
    "violet garlic",
    "violet ginger",
    "violet giraffe",
    "violet gorilla",
    "violet grapefruit",
    "violet grapes",
    "violet green bean",
    "violet guava",
    "violet hippo",
    "violet honeydew",
    "violet horse",
    "violet hummingbird",
    "violet kangaroo",
    "violet kiwi",
    "violet koala",
    "violet leek",
    "violet lemon",
    "violet lettuce",
    "violet lion",
    "violet mango",
    "violet mushroom",
    "violet onion",
    "violet orange",
    "violet orangutan",
    "violet owl",
    "violet panda",
    "violet papaya",
    "violet parrot",
    "violet passion fruit",
    "violet pea",
    "violet peach",
    "violet peacock",
    "violet pelican",
    "violet penguin",
    "violet persimmon",
    "violet pig",
    "violet pineapple",
    "violet plum",
    "violet polar bear",
    "violet pomegranate",
    "violet potato",
    "violet pumpkin",
    "violet rabbit",
    "violet radish",
    "violet raspberry",
    "violet rhino",
    "violet rooster",
    "violet sheep",
    "violet spinach",
    "violet squash",
    "violet strawberry",
    "violet swan",
    "violet sweet potato",
    "violet tiger",
    "violet tomato",
    "violet turnip",
    "violet watermelon",
    "violet wolf",
    "violet zebra",
    "violet zucchini",
    "violin",
    "volcano",
    "volleyball",
    "waffle",
    "wardrobe",
    "watch",
    "watercolor",
    "waterfall",
    "watermelon",
    "webcam",
    "whale",
    "wheelbarrow",
    "wheelchair",
    "whisk",
    "white apple",
    "white apricot",
    "white artichoke",
    "white asparagus",
    "white banana",
    "white bear",
    "white beet",
    "white bell pepper",
    "white bird",
    "white blackberry",
    "white blueberry",
    "white broccoli",
    "white brussels sprout",
    "white cabbage",
    "white cantaloupe",
    "white carrot",
    "white cat",
    "white cauliflower",
    "white celery",
    "white cheetah",
    "white cherry",
    "white chimp",
    "white coconut",
    "white corn",
    "white cow",
    "white cranberry",
    "white cucumber",
    "white date",
    "white deer",
    "white dog",
    "white dolphin",
    "white dragon fruit",
    "white duck",
    "white eagle",
    "white eggplant",
    "white elephant",
    "white fig",
    "white flamingo",
    "white fox",
    "white frog",
    "white garlic",
    "white ginger",
    "white giraffe",
    "white gorilla",
    "white grapefruit",
    "white grapes",
    "white green bean",
    "white guava",
    "white hippo",
    "white honeydew",
    "white horse",
    "white hummingbird",
    "white kangaroo",
    "white kiwi",
    "white koala",
    "white leek",
    "white lemon",
    "white lettuce",
    "white lion",
    "white mango",
    "white mushroom",
    "white onion",
    "white orange",
    "white orangutan",
    "white owl",
    "white panda",
    "white papaya",
    "white parrot",
    "white passion fruit",
    "white pea",
    "white peach",
    "white peacock",
    "white pelican",
    "white penguin",
    "white persimmon",
    "white pig",
    "white pineapple",
    "white plum",
    "white polar bear",
    "white pomegranate",
    "white potato",
    "white pumpkin",
    "white rabbit",
    "white radish",
    "white raspberry",
    "white rhino",
    "white rooster",
    "white sheep",
    "white spinach",
    "white squash",
    "white strawberry",
    "white swan",
    "white sweet potato",
    "white tiger",
    "white tomato",
    "white turnip",
    "white watermelon",
    "white wolf",
    "white zebra",
    "white zucchini",
    "whiteboard",
    "willow tree",
    "windmill",
    "wine glass",
    "wolf",
    "wooden bowl",
    "wooden box",
    "wooden cabinet",
    "wooden chair",
    "wooden cup",
    "wooden door",
    "wooden fork",
    "wooden frame",
    "wooden plate",
    "wooden sculpture",
    "wooden spoon",
    "wooden statue",
    "wooden table",
    "wooden vase",
    "wool bowl",
    "wool box",
    "wool cabinet",
    "wool chair",
    "wool cup",
    "wool door",
    "wool fork",
    "wool frame",
    "wool plate",
    "wool sculpture",
    "wool spoon",
    "wool statue",
    "wool table",
    "wool vase",
    "wreath",
    "wrench",
    "xylophone",
    "yacht",
    "yellow apple",
    "yellow apricot",
    "yellow artichoke",
    "yellow asparagus",
    "yellow banana",
    "yellow bear",
    "yellow beet",
    "yellow bell pepper",
    "yellow bird",
    "yellow blackberry",
    "yellow blueberry",
    "yellow broccoli",
    "yellow brussels sprout",
    "yellow cabbage",
    "yellow cantaloupe",
    "yellow carrot",
    "yellow cat",
    "yellow cauliflower",
    "yellow celery",
    "yellow cheetah",
    "yellow cherry",
    "yellow chimp",
    "yellow coconut",
    "yellow corn",
    "yellow cow",
    "yellow cranberry",
    "yellow cucumber",
    "yellow date",
    "yellow deer",
    "yellow dog",
    "yellow dolphin",
    "yellow dragon fruit",
    "yellow duck",
    "yellow eagle",
    "yellow eggplant",
    "yellow elephant",
    "yellow fig",
    "yellow flamingo",
    "yellow fox",
    "yellow frog",
    "yellow garlic",
    "yellow ginger",
    "yellow giraffe",
    "yellow gorilla",
    "yellow grapefruit",
    "yellow grapes",
    "yellow green bean",
    "yellow guava",
    "yellow hippo",
    "yellow honeydew",
    "yellow horse",
    "yellow hummingbird",
    "yellow kangaroo",
    "yellow kiwi",
    "yellow koala",
    "yellow leek",
    "yellow lemon",
    "yellow lettuce",
    "yellow lion",
    "yellow mango",
    "yellow mushroom",
    "yellow onion",
    "yellow orange",
    "yellow orangutan",
    "yellow owl",
    "yellow panda",
    "yellow papaya",
    "yellow parrot",
    "yellow passion fruit",
    "yellow pea",
    "yellow peach",
    "yellow peacock",
    "yellow pelican",
    "yellow penguin",
    "yellow persimmon",
    "yellow pig",
    "yellow pineapple",
    "yellow plum",
    "yellow polar bear",
    "yellow pomegranate",
    "yellow potato",
    "yellow pumpkin",
    "yellow rabbit",
    "yellow radish",
    "yellow raspberry",
    "yellow rhino",
    "yellow rooster",
    "yellow sheep",
    "yellow spinach",
    "yellow squash",
    "yellow strawberry",
    "yellow swan",
    "yellow sweet potato",
    "yellow tiger",
    "yellow tomato",
    "yellow turnip",
    "yellow watermelon",
    "yellow wolf",
    "yellow zebra",
    "yellow zucchini",
    "yo-yo",
    "yoga mat",
    "zebra",
    "zucchini",
]


def generate_images_parallel(objects_to_generate, output_dir: Path, num_gpus: int = 8):
    """并行生成图片"""
    print(f"\nGenerating {len(objects_to_generate)} retention images with {num_gpus} GPUs...")
    
    # 分配任务
    tasks_per_gpu = [[] for _ in range(num_gpus)]
    for i, obj in enumerate(objects_to_generate):
        tasks_per_gpu[i % num_gpus].append(obj)
    
    # 为每个 GPU 创建脚本
    processes = []
    for gpu_id in range(num_gpus):
        if not tasks_per_gpu[gpu_id]:
            continue
        
        script = f'''
import torch
from diffusers import AutoPipelineForText2Image
from pathlib import Path
import json

gpu_id = {gpu_id}
tasks = {json.dumps(tasks_per_gpu[gpu_id])}
output_dir = Path("{output_dir}")

torch.cuda.set_device(gpu_id)
pipe = AutoPipelineForText2Image.from_pretrained(
    "{SDXL_MODEL_PATH}",
    torch_dtype=torch.float16,
    variant="fp16"
).to(f"cuda:{{gpu_id}}")

for task in tasks:
    img_path = output_dir / f"object_{{task['idx']:04d}}.png"
    if img_path.exists():
        continue
    
    prompt = f"A high quality photo of {{task['name']}}, clean background, professional photography"
    image = pipe(prompt, num_inference_steps=4, guidance_scale=0.0).images[0]
    image.save(str(img_path))
    print(f"[GPU {{gpu_id}}] Generated: {{img_path.name}}")
'''
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
            f.write(script)
            script_path = f.name
        
        proc = subprocess.Popen(['python3', script_path])
        processes.append((proc, script_path))
    
    # 等待完成
    for proc, script_path in processes:
        proc.wait()
        os.unlink(script_path)
    
    print(f"✓ Generated {len(objects_to_generate)} images")


def generate_question_pool(objects: list, output_dir: Path):
    """生成题库"""
    print(f"\nGenerating question pool from {len(objects)} objects...")
    
    connectors = ["is", "shows", "depicts", "represents", "displays"]
    
    cw_pool = []
    mcq_i2d_pool = []
    mcq_d2i_pool = []
    
    n_objects = len(objects)
    # 每个物体生成多个变体，充分利用组合空间
    variants_per_object = max(20, n_objects)
    
    for obj in objects:
        idx = obj["idx"]
        name = obj["name"]
        img_path = obj["image_path"]
        other_objs = [o for o in objects if o["idx"] != idx]
        
        if len(other_objs) < 3:
            continue
        
        for v in range(variants_per_object):
            connector = connectors[v % len(connectors)]
            
            # CW 正样本
            cw_pool.append({
                "object_name": name,
                "image_path": img_path,
                "connector": connector,
                "label": "Correct"
            })
            
            # CW 负样本
            wrong_obj = random.choice(other_objs)
            cw_pool.append({
                "object_name": name,
                "image_path": wrong_obj["image_path"],
                "connector": connector,
                "label": "Wrong"
            })
            
            # MCQ I2D
            distractors = random.sample(other_objs, 3)
            choices = [name] + [d["name"] for d in distractors]
            random.shuffle(choices)
            correct_idx = choices.index(name)
            
            mcq_i2d_pool.append({
                "image_path": img_path,
                "connector": connector,
                "choices": choices,
                "correct_index": correct_idx
            })
            
            # MCQ D2I
            img_choices = [img_path] + [d["image_path"] for d in distractors]
            random.shuffle(img_choices)
            correct_img_idx = img_choices.index(img_path)
            
            mcq_d2i_pool.append({
                "description": name,
                "connector": connector,
                "image_choices": img_choices,
                "correct_index": correct_img_idx
            })
    
    # 打乱
    random.shuffle(cw_pool)
    random.shuffle(mcq_i2d_pool)
    random.shuffle(mcq_d2i_pool)
    
    # 分割 train/val (95/5)
    def split_data(data, val_ratio=0.05):
        n_val = max(10, int(len(data) * val_ratio))
        return data[n_val:], data[:n_val]
    
    cw_train, cw_val = split_data(cw_pool)
    mcq_i2d_train, mcq_i2d_val = split_data(mcq_i2d_pool)
    mcq_d2i_train, mcq_d2i_val = split_data(mcq_d2i_pool)
    
    # 保存
    with open(output_dir / "cw_train.jsonl", "w") as f:
        for s in cw_train:
            f.write(json.dumps(s) + "\n")
    
    with open(output_dir / "cw_val.jsonl", "w") as f:
        for s in cw_val:
            f.write(json.dumps(s) + "\n")
    
    with open(output_dir / "mcq_i2d_train.jsonl", "w") as f:
        for s in mcq_i2d_train:
            f.write(json.dumps(s) + "\n")
    
    with open(output_dir / "mcq_i2d_val.jsonl", "w") as f:
        for s in mcq_i2d_val:
            f.write(json.dumps(s) + "\n")
    
    with open(output_dir / "mcq_d2i_train.jsonl", "w") as f:
        for s in mcq_d2i_train:
            f.write(json.dumps(s) + "\n")
    
    with open(output_dir / "mcq_d2i_val.jsonl", "w") as f:
        for s in mcq_d2i_val:
            f.write(json.dumps(s) + "\n")
    
    # 保存元信息
    meta = {
        "num_objects": len(objects),
        "variants_per_object": variants_per_object,
        "cw_train": len(cw_train),
        "cw_val": len(cw_val),
        "mcq_i2d_train": len(mcq_i2d_train),
        "mcq_i2d_val": len(mcq_i2d_val),
        "mcq_d2i_train": len(mcq_d2i_train),
        "mcq_d2i_val": len(mcq_d2i_val),
    }
    with open(output_dir / "pool_meta.json", "w") as f:
        json.dump(meta, f, indent=2)
    
    print(f"✓ Question pool generated:")
    print(f"  CW: {len(cw_train)} train + {len(cw_val)} val")
    print(f"  MCQ I2D: {len(mcq_i2d_train)} train + {len(mcq_i2d_val)} val")
    print(f"  MCQ D2I: {len(mcq_d2i_train)} train + {len(mcq_d2i_val)} val")
    print(f"  Total: {len(cw_train) + len(mcq_i2d_train) + len(mcq_d2i_train)} train samples")


def main():
    parser = argparse.ArgumentParser(description="生成 Retention 题库（一次生成，永久复用）")
    parser.add_argument("--num_objects", type=int, default=200, help="生成的物体数量")
    parser.add_argument("--output_dir", type=str, default="data/object_retention_pool", help="输出目录")
    parser.add_argument("--num_gpus", type=int, default=8, help="并行 GPU 数量")
    parser.add_argument("--seed", type=int, default=42, help="随机种子")
    args = parser.parse_args()
    
    random.seed(args.seed)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    images_dir = output_dir / "images"
    images_dir.mkdir(exist_ok=True)
    
    print("="*60)
    print("Generating Retention Pool (one-time, reusable)")
    print("="*60)
    print(f"  Objects: {args.num_objects}")
    print(f"  Output: {output_dir}")
    
    # 选择物体
    if args.num_objects > len(COMMON_OBJECTS):
        print(f"⚠️ Requested {args.num_objects} objects, but only {len(COMMON_OBJECTS)} available")
        args.num_objects = len(COMMON_OBJECTS)
    
    selected_objects = random.sample(COMMON_OBJECTS, args.num_objects)
    
    # 准备任务
    objects_to_generate = []
    objects_meta = []
    for i, name in enumerate(selected_objects):
        img_path = str(images_dir / f"object_{i:04d}.png")
        objects_to_generate.append({"idx": i, "name": name})
        objects_meta.append({
            "idx": i,
            "name": name,
            "image_path": img_path
        })
    
    # 保存物体元信息
    with open(output_dir / "objects.json", "w") as f:
        json.dump(objects_meta, f, indent=2)
    
    # 生成图片
    generate_images_parallel(objects_to_generate, images_dir, args.num_gpus)
    
    # 生成题库
    generate_question_pool(objects_meta, output_dir)
    
    print("\n" + "="*60)
    print("✅ Retention pool generated successfully!")
    print(f"   Location: {output_dir}")
    print("   This pool can be reused for any number of entities.")
    print("="*60)


if __name__ == "__main__":
    main()

# === PATCH: 添加 prompt 变体支持 ===
PROMPT_TEMPLATES = [
    "A high quality photo of {obj}, clean background, professional photography",
    "A detailed photograph of {obj}, studio lighting, white background",
    "A clear image of {obj}, product photography style",
    "{obj}, realistic photo, 4k resolution, sharp focus",
    "Professional photo of {obj}, centered, neutral background",
    "A beautiful {obj}, high resolution, photography",
    "{obj} on white background, professional shot",
    "Close-up photo of {obj}, studio quality",
    "Artistic photo of {obj}, soft lighting",
    "{obj}, professional product photography, clean",
    "High definition photo of {obj}, professional",
    "A {obj}, photographed professionally, detailed",
    "Photo of {obj}, sharp, high quality image",
    "{obj}, realistic rendering, studio photo",
    "Professional image of {obj}, clean backdrop",
    "Detailed shot of {obj}, professional lighting",
    "{obj}, 4k photo, professional quality",
    "A stunning photo of {obj}, high resolution",
    "Clear photograph of {obj}, professional",
    "Studio photo of {obj}, white background",
]
